# wayfinder/backend/nixpacks.toml
[providers]
node = { npxPlaywrightInstall = false } # Disable the generic multi-browser setup script

[phases.setup]
# FORCE THE PACKAGER TO EXCLUSIVELY BUILD HEADLESS CHROMIUM:
cmds = ["npm ci", "npx playwright install chromium"]
